---

# Creates datatable: country_table
table:
- country: AFG
  country_name: Afghanistan
  region: EMRO
- country: AGO
  country_name: Angola
  region: AFRO
- country: ALB
  country_name: Albania
  region: EURO
- country: AND
  country_name: Andorra
  region: EURO
- country: ARE
  country_name: United Arab Emirates
  region: EMRO
- country: ARG
  country_name: Argentina
  region: PAHO
- country: ARM
  country_name: Armenia
  region: EURO
- country: ATG
  country_name: Antigua and Barbuda
  region: PAHO
- country: AUS
  country_name: Australia
  region: WPRO
- country: AUT
  country_name: Austria
  region: EURO
- country: AZE
  country_name: Azerbaijan
  region: EURO
- country: BDI
  country_name: Burundi
  region: AFRO
- country: BEL
  country_name: Belgium
  region: EURO
- country: BEN
  country_name: Benin
  region: AFRO
- country: BFA
  country_name: Burkina Faso
  region: AFRO
- country: BGD
  country_name: Bangladesh
  region: SEARO
- country: BGR
  country_name: Bulgaria
  region: EURO
- country: BHR
  country_name: Bahrain
  region: EMRO
- country: BHS
  country_name: Bahamas
  gbd_alt_name: The Bahamas
  region: PAHO
- country: BIH
  country_name: Bosnia and Herzegovina
  region: EURO
- country: BLR
  country_name: Belarus
  region: EURO
- country: BLZ
  country_name: Belize
  region: PAHO
- country: BOL
  country_name: Bolivia (Plurinational State of)
  gbd_alt_name: Bolivia
  region: PAHO
- country: BRA
  country_name: Brazil
  region: PAHO
- country: BRB
  country_name: Barbados
  region: PAHO
- country: BRN
  country_name: Brunei Darussalam
  gbd_alt_name: Brunei
  region: WPRO
- country: BTN
  country_name: Bhutan
  region: SEARO
- country: BWA
  country_name: Botswana
  region: AFRO
- country: CAF
  country_name: Central African Republic
  region: AFRO
- country: CAN
  country_name: Canada
  region: PAHO
- country: CHE
  country_name: Switzerland
  region: EURO
- country: CHL
  country_name: Chile
  region: PAHO
- country: CHN
  country_name: China
  region: WPRO
- country: CIV
  country_name: Côte d'Ivoire
  region: AFRO
- country: CMR
  country_name: Cameroon
  region: AFRO
- country: COD
  country_name: Democratic Republic of the Congo
  gbd_alt_name: DR Congo
  region: AFRO
- country: COG
  country_name: Congo
  gbd_alt_name: Congo (Brazzaville)
  region: AFRO
- country: COK
  country_name: Cook Islands
  region: WPRO
- country: COL
  country_name: Colombia
  region: PAHO
- country: COM
  country_name: Comoros
  region: AFRO
- country: CPV
  country_name: Cabo Verde
  gbd_alt_name: Cape Verde
  region: AFRO
- country: CRI
  country_name: Costa Rica
  region: PAHO
- country: CUB
  country_name: Cuba
  region: PAHO
- country: CYP
  country_name: Cyprus
  region: EURO
- country: CZE
  country_name: Czechia
  gbd_alt_name: Czech Republic
  region: EURO
- country: DEU
  country_name: Germany
  region: EURO
- country: DJI
  country_name: Djibouti
  region: EMRO
- country: DMA
  country_name: Dominica
  region: PAHO
- country: DNK
  country_name: Denmark
  region: EURO
- country: DOM
  country_name: Dominican Republic
  region: PAHO
- country: DZA
  country_name: Algeria
  region: AFRO
- country: ECU
  country_name: Ecuador
  region: PAHO
- country: EGY
  country_name: Egypt
  region: EMRO
- country: ERI
  country_name: Eritrea
  region: AFRO
- country: ESP
  country_name: Spain
  region: EURO
- country: EST
  country_name: Estonia
  region: EURO
- country: ETH
  country_name: Ethiopia
  region: AFRO
- country: FIN
  country_name: Finland
  region: EURO
- country: FJI
  country_name: Fiji
  region: WPRO
- country: FRA
  country_name: France
  region: EURO
- country: FSM
  country_name: Micronesia (Federated States of)
  gbd_alt_name: Federated States of Micronesia
  region: WPRO
- country: GAB
  country_name: Gabon
  region: AFRO
- country: GBR
  country_name: United Kingdom
  gbd_alt_name: UK
  region: EURO
- country: GEO
  country_name: Georgia
  region: EURO
- country: GHA
  country_name: Ghana
  region: AFRO
- country: GIN
  country_name: Guinea
  region: AFRO
- country: GMB
  country_name: Gambia
  gbd_alt_name: The Gambia
  region: AFRO
- country: GNB
  country_name: Guinea-Bissau
  region: AFRO
- country: GNQ
  country_name: Equatorial Guinea
  region: AFRO
- country: GRC
  country_name: Greece
  region: EURO
- country: GRD
  country_name: Grenada
  region: PAHO
- country: GTM
  country_name: Guatemala
  region: PAHO
- country: GUY
  country_name: Guyana
  region: PAHO
- country: HND
  country_name: Honduras
  region: PAHO
- country: HRV
  country_name: Croatia
  region: EURO
- country: HTI
  country_name: Haiti
  region: PAHO
- country: HUN
  country_name: Hungary
  region: EURO
- country: IDN
  country_name: Indonesia
  region: SEARO
- country: IND
  country_name: India
  region: SEARO
- country: IRL
  country_name: Ireland
  region: EURO
- country: IRN
  country_name: Iran (Islamic Republic of)
  gbd_alt_name: Iran
  region: EMRO
- country: IRQ
  country_name: Iraq
  region: EMRO
- country: ISL
  country_name: Iceland
  region: EURO
- country: ISR
  country_name: Israel
  region: EURO
- country: ITA
  country_name: Italy
  region: EURO
- country: JAM
  country_name: Jamaica
  region: PAHO
- country: JOR
  country_name: Jordan
  region: EMRO
- country: JPN
  country_name: Japan
  region: WPRO
- country: KAZ
  country_name: Kazakhstan
  region: EURO
- country: KEN
  country_name: Kenya
  region: AFRO
- country: KGZ
  country_name: Kyrgyzstan
  region: EURO
- country: KHM
  country_name: Cambodia
  region: WPRO
- country: KIR
  country_name: Kiribati
  region: WPRO
- country: KNA
  country_name: Saint Kitts and Nevis
  region: PAHO
- country: KOR
  country_name: Republic of Korea
  gbd_alt_name: South Korea
  region: WPRO
- country: KWT
  country_name: Kuwait
  region: EMRO
- country: LAO
  country_name: Lao People's Democratic Republic
  gbd_alt_name: Laos
  region: WPRO
- country: LBN
  country_name: Lebanon
  region: EMRO
- country: LBR
  country_name: Liberia
  region: AFRO
- country: LBY
  country_name: Libya
  region: EMRO
- country: LCA
  country_name: Saint Lucia
  region: PAHO
- country: LKA
  country_name: Sri Lanka
  region: SEARO
- country: LSO
  country_name: Lesotho
  region: AFRO
- country: LTU
  country_name: Lithuania
  region: EURO
- country: LUX
  country_name: Luxembourg
  region: EURO
- country: LVA
  country_name: Latvia
  region: EURO
- country: MAR
  country_name: Morocco
  region: EMRO
- country: MCO
  country_name: Monaco
  region: EURO
- country: MDA
  country_name: Republic of Moldova
  gbd_alt_name: Moldova
  region: EURO
- country: MDG
  country_name: Madagascar
  region: AFRO
- country: MDV
  country_name: Maldives
  region: SEARO
- country: MEX
  country_name: Mexico
  region: PAHO
- country: MHL
  country_name: Marshall Islands
  region: WPRO
- country: MKD
  country_name: North Macedonia
  region: EURO
- country: MLI
  country_name: Mali
  region: AFRO
- country: MLT
  country_name: Malta
  region: EURO
- country: MMR
  country_name: Myanmar
  region: SEARO
- country: MNE
  country_name: Montenegro
  region: EURO
- country: MNG
  country_name: Mongolia
  region: WPRO
- country: MOZ
  country_name: Mozambique
  region: AFRO
- country: MRT
  country_name: Mauritania
  region: AFRO
- country: MUS
  country_name: Mauritius
  region: AFRO
- country: MWI
  country_name: Malawi
  region: AFRO
- country: MYS
  country_name: Malaysia
  region: WPRO
- country: NAM
  country_name: Namibia
  region: AFRO
- country: NER
  country_name: Niger
  region: AFRO
- country: NGA
  country_name: Nigeria
  region: AFRO
- country: NIC
  country_name: Nicaragua
  region: PAHO
- country: NIU
  country_name: Niue
  region: WPRO
- country: NLD
  country_name: Netherlands
  region: EURO
- country: NOR
  country_name: Norway
  region: EURO
- country: NPL
  country_name: Nepal
  region: SEARO
- country: NRU
  country_name: Nauru
  region: WPRO
- country: NZL
  country_name: New Zealand
  region: WPRO
- country: OMN
  country_name: Oman
  region: EMRO
- country: PAK
  country_name: Pakistan
  region: EMRO
- country: PAN
  country_name: Panama
  region: PAHO
- country: PER
  country_name: Peru
  region: PAHO
- country: PHL
  country_name: Philippines
  region: WPRO
- country: PLW
  country_name: Palau
  region: WPRO
- country: PNG
  country_name: Papua New Guinea
  region: WPRO
- country: POL
  country_name: Poland
  region: EURO
- country: PRK
  country_name: Democratic People's Republic of Korea
  gbd_alt_name: North Korea
  region: SEARO
- country: PRT
  country_name: Portugal
  region: EURO
- country: PRY
  country_name: Paraguay
  region: PAHO
- country: QAT
  country_name: Qatar
  region: EMRO
- country: ROU
  country_name: Romania
  region: EURO
- country: RUS
  country_name: Russian Federation
  gbd_alt_name: Russia
  region: EURO
- country: RWA
  country_name: Rwanda
  region: AFRO
- country: SAU
  country_name: Saudi Arabia
  region: EMRO
- country: SDN
  country_name: Sudan
  region: EMRO
- country: SEN
  country_name: Senegal
  region: AFRO
- country: SGP
  country_name: Singapore
  region: WPRO
- country: SLB
  country_name: Solomon Islands
  region: WPRO
- country: SLE
  country_name: Sierra Leone
  region: AFRO
- country: SLV
  country_name: El Salvador
  region: PAHO
- country: SMR
  country_name: San Marino
  region: EURO
- country: SOM
  country_name: Somalia
  region: EMRO
- country: SRB
  country_name: Serbia
  region: EURO
- country: SSD
  country_name: South Sudan
  region: EMRO
- country: STP
  country_name: Sao Tome and Principe
  gbd_alt_name: São Tomé and PrÍncipe
  region: AFRO
- country: SUR
  country_name: Suriname
  region: PAHO
- country: SVK
  country_name: Slovakia
  region: EURO
- country: SVN
  country_name: Slovenia
  region: EURO
- country: SWE
  country_name: Sweden
  region: EURO
- country: SWZ
  country_name: Eswatini
  gbd_alt_name: eSwatini
  region: AFRO
- country: SYC
  country_name: Seychelles
  region: AFRO
- country: SYR
  country_name: Syrian Arab Republic
  gbd_alt_name: Syria
  region: EMRO
- country: TCD
  country_name: Chad
  region: AFRO
- country: TGO
  country_name: Togo
  region: AFRO
- country: THA
  country_name: Thailand
  region: SEARO
- country: TJK
  country_name: Tajikistan
  region: EURO
- country: TKM
  country_name: Turkmenistan
  region: EURO
- country: TLS
  country_name: Timor-Leste
  region: SEARO
- country: TON
  country_name: Tonga
  region: WPRO
- country: TTO
  country_name: Trinidad and Tobago
  region: PAHO
- country: TUN
  country_name: Tunisia
  region: EMRO
- country: TUR
  country_name: Turkey
  region: EURO
- country: TUV
  country_name: Tuvalu
  region: WPRO
- country: TZA
  country_name: United Republic of Tanzania
  gbd_alt_name: Tanzania
  region: AFRO
- country: UGA
  country_name: Uganda
  region: AFRO
- country: UKR
  country_name: Ukraine
  region: EURO
- country: URY
  country_name: Uruguay
  region: PAHO
- country: USA
  country_name: United States of America
  gbd_alt_name: USA
  region: PAHO
- country: UZB
  country_name: Uzbekistan
  region: EURO
- country: VCT
  country_name: Saint Vincent and the Grenadines
  region: PAHO
- country: VEN
  country_name: Venezuela (Bolivarian Republic of)
  gbd_alt_name: Venezuela
  region: PAHO
- country: VNM
  country_name: Viet Nam
  gbd_alt_name: Vietnam
  region: WPRO
- country: VUT
  country_name: Vanuatu
  region: WPRO
- country: WSM
  country_name: Samoa
  region: WPRO
- country: YEM
  country_name: Yemen
  region: EMRO
- country: ZAF
  country_name: South Africa
  region: AFRO
- country: ZMB
  country_name: Zambia
  region: AFRO
- country: ZWE
  country_name: Zimbabwe
  region: AFRO
