---

# Creates datatable: d_v_a_table
table:
- d_v_a_id: 1
  disease: HepB
  vaccine: HepB
  activity: routine
- d_v_a_id: 2
  disease: HepB
  vaccine: HepB_BD
  activity: routine
- d_v_a_id: 3
  disease: Hib
  vaccine: Hib3
  activity: routine
# - d_v_a_id: 4
#   disease: HPV
#   vaccine: HPV
#   activity: routine
- d_v_a_id: 4
  disease: Measles
  vaccine: MCV1
  activity: routine
- d_v_a_id: 5
  disease: Measles
  vaccine: MCV2
  activity: routine
- d_v_a_id: 6
  disease: Measles
  vaccine: Measles
  activity: campaign
- d_v_a_id: 7
  disease: PCV
  vaccine: PCV3
  activity: routine
- d_v_a_id: 8
  disease: Rota
  vaccine: Rota
  activity: routine
- d_v_a_id: 9
  disease: Rubella
  vaccine: RCV2
  activity: routine
- d_v_a_id: 10
  disease: Rubella
  vaccine: Rubella
  activity: routine
- d_v_a_id: 11
  disease: Rubella
  vaccine: Rubella
  activity: campaign
- d_v_a_id: 12
  disease: Dip
  vaccine: Dip3
  activity: all
- d_v_a_id: 13
  disease: Dip
  vaccine: Dip_BX
  activity: all
- d_v_a_id: 14
  disease: Tet
  vaccine: Tet3
  activity: all
- d_v_a_id: 15
  disease: Tet
  vaccine: Tet_BX
  activity: all
- d_v_a_id: 16
  disease: Per
  vaccine: Per3
  activity: all
- d_v_a_id: 17
  disease: Per
  vaccine: Per_BX
  activity: all
- d_v_a_id: 18
  disease: TB
  vaccine: BCG
  activity: all
