---

# Creates datatable: d_v_a_table
table:
- d_v_a_id: 1
  disease: HepB
  vaccine: HepB
  activity: routine
  d_v_a_name: "Hepatitis B"
- d_v_a_id: 2
  disease: HepB
  vaccine: HepB_BD
  activity: routine
  d_v_a_name: "Hepatitis B (birth dose)"
- d_v_a_id: 3
  disease: Hib
  vaccine: Hib3
  activity: routine
  d_v_a_name: "Haemophilus influenzae type b"
- d_v_a_id: 4
  disease: Measles
  vaccine: MCV1
  activity: routine
  d_v_a_name: "Measles (first dose)"
- d_v_a_id: 5
  disease: Measles
  vaccine: MCV2
  activity: routine
  d_v_a_name: "Measles (second dose)"
- d_v_a_id: 6
  disease: Measles
  vaccine: Measles
  activity: campaign
  d_v_a_name: "Measles (campaign)"
- d_v_a_id: 7
  disease: PCV
  vaccine: PCV3
  activity: routine
  d_v_a_name: "Pneumococcal"
- d_v_a_id: 8
  disease: Rota
  vaccine: Rota
  activity: routine
  d_v_a_name: "Rotavirus"
- d_v_a_id: 9
  disease: Rubella
  vaccine: Rubella
  activity: routine
  d_v_a_name: "Rubella (first dose)"
- d_v_a_id: 10
  disease: Rubella
  vaccine: RCV2
  activity: routine
  d_v_a_name: "Rubella (second dose)"
- d_v_a_id: 11
  disease: Rubella
  vaccine: Rubella
  activity: campaign
  d_v_a_name: "Rubella (campaign)"
- d_v_a_id: 12
  disease: Dip
  vaccine: Dip3
  activity: all
  d_v_a_name: "Diphtheria"
- d_v_a_id: 13
  disease: Dip
  vaccine: Dip_BX
  activity: all
  d_v_a_name: "Diphtheria (booster)"
- d_v_a_id: 14
  disease: Tet
  vaccine: Tet3
  activity: all
  d_v_a_name: "Tetanus"
- d_v_a_id: 15
  disease: Tet
  vaccine: Tet_BX
  activity: all
  d_v_a_name: "Tetanus (booster)"
- d_v_a_id: 16
  disease: Per
  vaccine: wPer3
  activity: all 
  d_v_a_name: "Pertussis whole-cell"
- d_v_a_id: 17
  disease: Per
  vaccine: aPer3
  activity: all
  d_v_a_name: "Pertussis acellular"
- d_v_a_id: 18
  disease: Per
  vaccine: aPer_BX
  activity: all
  d_v_a_name: "Pertussis (booster)"
- d_v_a_id: 19
  disease: TB
  vaccine: BCG
  activity: all
  d_v_a_name: "Tuberculosis (BCG)"
- d_v_a_id: 20
  disease: xxxPolio
  vaccine: xxxPolio
  activity: all
  d_v_a_name: "xxxPolio"
- d_v_a_id: 21
  disease: xxxMeasles
  vaccine: xxxMeasles
  activity: all
  d_v_a_name: "xxxMeasles"
