---

# Creates datatable: d_v_a_table
table:
- d_v_a_id: 1
  disease: HepB
  vaccine: HepB
  activity: routine
- d_v_a_id: 2
  disease: HepB
  vaccine: HepB_BD
  activity: routine
- d_v_a_id: 3
  disease: Hib
  vaccine: Hib3
  activity: routine
- d_v_a_id: 4
  disease: HPV
  vaccine: HPV
  activity: routine
- d_v_a_id: 5
  disease: Measles
  vaccine: MCV1
  activity: routine
- d_v_a_id: 6
  disease: Measles
  vaccine: MCV2
  activity: routine
- d_v_a_id: 7
  disease: Measles
  vaccine: Measles
  activity: campaign
- d_v_a_id: 8
  disease: PCV
  vaccine: PCV3
  activity: routine
- d_v_a_id: 9
  disease: Rota
  vaccine: Rota
  activity: routine
- d_v_a_id: 10
  disease: Rubella
  vaccine: RCV2
  activity: routine
- d_v_a_id: 11
  disease: Rubella
  vaccine: Rubella
  activity: routine
- d_v_a_id: 12
  disease: Rubella
  vaccine: Rubella
  activity: campaign
- d_v_a_id: 13
  disease: YF
  vaccine: YF
  activity: routine
- d_v_a_id: 14
  disease: YF
  vaccine: YF
  activity: campaign
- d_v_a_id: 15
  disease: Dip
  vaccine: DTP3
  activity: routine
- d_v_a_id: 16
  disease: Dip
  vaccine: Dip
  activity: campaign
- d_v_a_id: 17
  disease: Tet
  vaccine: DTP3
  activity: routine
- d_v_a_id: 18
  disease: Tet
  vaccine: Tet
  activity: campaign
- d_v_a_id: 19
  disease: Per
  vaccine: DTP3
  activity: routine
- d_v_a_id: 20
  disease: Per
  vaccine: Per
  activity: campaign
- d_v_a_id: 21
  disease: TB
  vaccine: BCG
  activity: routine
- d_v_a_id: 22
  disease: TB
  vaccine: BCG
  activity: campaign
