---

# Creates datatable: disease_table
table:
- disease: HepB
  disease_name: "Hepatitis B"
  source: vimc
- disease: Hib
  disease_name: "Haemophilus influenzae type b"
  source: vimc
- disease: PCV
  disease_name: "Pneumococcal"
  source: vimc
- disease: Rota
  disease_name: "Rotavirus"
  source: vimc
- disease: Rubella
  disease_name: "Rubella"
  source: vimc
- disease: Dip
  disease_name: "Diphtheria"
  source: static
- disease: Tet
  disease_name: "Tetanus"
  source: static
- disease: Per
  disease_name: "Pertussis"
  source: static
- disease: TB
  disease_name: "Tuberculosis"
  source: static
- disease: Measles
  disease_name: "Measles"
  source: extern
# - disease: Polio
#   disease_name: "Poliomyelitis"
#   source: extern
