---

# Creates datatable: extern_models_table
table:

- model: dynamice
  disease: "measles"
  weight: 1
  
- model: measles
  disease: "measles"
  weight: 1

- model: polio
  disease: "polio"
  weight: 1
