---

# Creates datatable: gapminder_dict_table
table:

- var: gini
  file: "gapminder_gini"

- var: pop_density 
  file: "population_density_per_square_km"

- var: urban_percent
  file: "urban_population_percent_of_total"

- var: maternal_mortality
  file: "maternal_mortality_ratio_who"

- var: private_health
  file: "private_share_of_total_health_spending_percent"

- var: basic_water
  file: "at_least_basic_water_source_overall_access_percent"
