---

# Creates datatable: gbd_dict_table
table:

- disease: dip
  gbd_name: "Diphtheria"
  
- disease: tet
  gbd_name: "Tetanus"
  
- disease: per
  gbd_name: "Pertussis" # GBD19 uses "Whooping cough"
  
- disease: tb
  gbd_name: "Tuberculosis"
