---

# Creates datatable: metric_dict_table
table:

- metric: deaths
  metric_long: "Premature deaths"
  metric_short: "Deaths"
  
- metric: dalys
  metric_long: "Disability-adjusted life years"
  metric_short: "DALYs"
