---

# Creates datatable: region_dict_table
table:

- region: AFR
  region_name: "African region"
  
- region: AMR
  region_name: "Region of the Americas"
  
- region: EMR
  region_name: "Eastern Mediterranean region"
  
- region: EUR
  region_name: "European region"
  
- region: SEAR
  region_name: "South-East Asia region"
  
- region: WPR
  region_name: "Western Pacific region"
