---

# Creates datatable: regimen_table
table:

- vaccine: hepb
  schedule: 3
  
- vaccine: hepb_bd
  schedule: 1
  
- vaccine: hib
  schedule: 3
  
- vaccine: je
  schedule: 2
  
- vaccine: mena
  schedule: 2
  
- vaccine: pcv
  schedule: 3
  
- vaccine: rota
  schedule: 3
  
- vaccine: rubella
  schedule: 2
  
- vaccine: yf
  schedule: 1
  
- vaccine: dip
  schedule: 3
  
- vaccine: dip_bx
  schedule: 3
  
- vaccine: tet
  schedule: 3
  
- vaccine: tet_bx
  schedule: 3
  
- vaccine: tet_px
  schedule: 1
  
- vaccine: wper
  schedule: 3
  
- vaccine: aper
  schedule: 3
  
- vaccine: aper_bx
  schedule: 3
  
- vaccine: bcg
  schedule: 1
  
- vaccine: mcv1
  schedule: 1
  
- vaccine: mcv2
  schedule: 1
  
- vaccine: measles
  schedule: 2
  
- vaccine: ipv
  schedule: 4
  
- vaccine: opv
  schedule: 4
