---

# Creates datatable: type_name_table
table:

- type: dip
  type_name: "Diphtheria-containing vaccine"
  
- type: tet
  type_name: "Tetanus-containing vaccine"
  
- type: wper
  type_name: "Whole-cell pertussis-containing vaccine"
  
- type: aper
  type_name: "Acellular pertussis-containing vaccine"
  
- type: bcg
  type_name: "Bacille Calmette-Guerin"
