---

# Creates datatable: vaccine_schedule_table
table:
- vaccine: HepB
  schedule: 3
- vaccine: HepB_BD
  schedule: 1
- vaccine: Hib3
  schedule: 3
- vaccine: HPV
  schedule: 2
- vaccine: Measles
  schedule: 2
- vaccine: PCV3
  schedule: 4
- vaccine: Rota
  schedule: 3
- vaccine: Rubella
  schedule: 2
- vaccine: YF
  schedule: 1
- vaccine: DTP3
  schedule: 5
- vaccine: Dip
  schedule: 5
- vaccine: Tet
  schedule: 5
- vaccine: BCG
  schedule: 1
