---

# Creates datatable: vaccine_table
table:
- vaccine: HepB
  vaccine_name: "Hepatitis B"
  age: 0
- vaccine: HepB_BD
  vaccine_name: "Hep B birth dose"
  age: 0
- vaccine: Hib3
  vaccine_name: "Haemophilus influenzae type b"
  age: 0
- vaccine: PCV3
  vaccine_name: "Pneumococcal"
  age: 0
- vaccine: RCV2
  vaccine_name: "Rubella-containing"
  age: 0
- vaccine: Rota
  vaccine_name: "Rotavirus"
  age: 0
- vaccine: Rubella
  vaccine_name: "Rubella"
  age: 0
- vaccine: Dip3
  vaccine_name: "Diphtheria primary"
  age: 0
- vaccine: Dip_BX
  vaccine_name: "Diphtheria booster"
  age: "1:15"
- vaccine: Tet3
  vaccine_name: "Tetanus primary"
  age: 0
- vaccine: Tet_BX
  vaccine_name: "Tetanus booster"
  age: "1:15"
- vaccine: wPer3
  vaccine_name: "Whole-cell pertussis"
  age: 0
- vaccine: aPer3
  vaccine_name: "Acellular pertussis primary"
  age: 0
- vaccine: aPer_BX
  vaccine_name: "Acellular pertussis booster"
  age: "1:15"
- vaccine: BCG
  vaccine_name: "Bacille Calmette-Guerin"
  age: 0
- vaccine: MCV1
  vaccine_name: "Measles first dose"
  age: 1
- vaccine: MCV2
  vaccine_name: "Measles second dose"
  age: "4:6"
- vaccine: Measles
  vaccine_name: "Measles"
  age: "4:6"

# Source for DTP-containing booster dose age groups:
#   https://terrance.who.int/mediacentre/data/sage/SAGE_Docs_Ppt_Apr2017/10_session_diptheria/Apr2017_session10_diphtheria_vax_effectiveness.pdf
