---

# Creates datatable: vaccine_schedule_table
table:
- vaccine: HepB
  schedule: 3
- vaccine: HepB_BD
  schedule: 1
- vaccine: Hib3
  schedule: 3
# - vaccine: HPV
#   schedule: 2
- vaccine: MCV1
  schedule: 1
- vaccine: MCV2
  schedule: 2
- vaccine: Measles
  schedule: 2
- vaccine: PCV3
  schedule: 3
- vaccine: RCV2
  schedule: 2
- vaccine: Rota
  schedule: 3
- vaccine: Rubella
  schedule: 2
- vaccine: Dip
  schedule: 3
- vaccine: Tet
  schedule: 3
- vaccine: Per
  schedule: 3
- vaccine: BCG
  schedule: 1
