---

# Creates datatable: vaccine_wiise_table
table:
- intervention: bcg
  vaccine: BCG
  age: "0"
- intervention: dtpcv3
  vaccine: DTP3
  age: "0"
- intervention: hepb3
  vaccine: HepB
  age: "0"
- intervention: hepb_bd
  vaccine: HepB_BD
  age: "0"
- intervention: hib3
  vaccine: Hib3
  age: "0"
- intervention: mcv1
  vaccine: MCV1
  age: "0"
- intervention: mcv2
  vaccine: MCV2
  age: "0"
- intervention: pcv3
  vaccine: PCV3
  age: "0"
- intervention: rcv1
  vaccine: Rubella
  age: "0"
- intervention: rotac
  vaccine: Rota
  age: "0"
- intervention: yfv
  vaccine: YF
  age: "0"
