---

# Creates datatable: vaccine_efficacy_table
table:
- vaccine: Dip3
  efficacy: 0.969 # https://apps.who.int/iris/bitstream/handle/10665/258681/WER9231.pdf?sequence=1
  lower: 0.943
  upper: 0.984
- vaccine: Dip_BX
  efficacy: 0.969 # Placeholder
  lower: 0.943
  upper: 0.984
- vaccine: Tet3
  efficacy: 0.99 # https://apps.who.int/iris/bitstream/handle/10665/233093/WER8120_198-208.PDF
  lower: 0.8
  upper: 1.0
- vaccine: Tet_BX
  efficacy: 0.99 # Placeholder
  lower: 0.8
  upper: 1.0
- vaccine: Per3
  efficacy: 0.8 # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5088088/
  lower: 0.71
  upper: 0.86
  decay_x: 5 # (in years) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6547082/
  decay_y: 0.49 # (0.75 * 0.65) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6547082/
- vaccine: Per_BX
  efficacy: 0.8 # Placeholder
  lower: 0.71
  upper: 0.86
- vaccine: BCG
  efficacy: 0.66 # https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-016-0685-4
  lower: 0.08
  upper: 0.88
