---

# Creates datatable: wiise_table
table:
- wiise_id: BCG
  vaccine: BCG
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: DTPCV3
  vaccine: DTP3
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: HEPB3
  vaccine: HepB
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: HEPB_BD
  vaccine: HepB_BD
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: HIB3
  vaccine: Hib3
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: MCV1
  vaccine: MCV1
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: MCV2
  vaccine: MCV2
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: PCV3
  vaccine: PCV3
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: RCV1
  vaccine: Rubella
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: ROTAC
  vaccine: Rota
  activity: routine
  coverage_category: WUENIC
  age: "0"
- wiise_id: YFV
  vaccine: YF
  activity: routine
  coverage_category: WUENIC
  age: "0"
