---

# Creates datatable: wpp_dict_table
table:

- metric: pop
  var: "pop"
  file: "pop"
  scale: 1000
  proj: yes
  age: yes
  
- metric: deaths
  var: "mxB"
  file: "mx"
  scale: "pop"
  proj: no
  age: yes
  
- metric: life_exp
  var: "e0B"
  file: "e0"
  scale: 1
  proj: yes
  age: no
  
- metric: fertility
  var: "pasfr"
  file: "percentASFR"
  scale: 0.01
  proj: no
  age: yes
