---

# Creates datatable: wpp_dict_table
table:

- metric: pop
  var: "pop"
  country_code: 4
  country_name: "Afghanistan"
  region: EMRO
  
# - country: AGO
#   country_code: 24
#   country_name: "Angola"
#   region: AFRO
  
  

    # pop = list(
    #   var   = "pop",
    #   file  = "pop",
    #   scale = 1e3,
    #   proj  = TRUE,
    #   age   = TRUE),
    # deaths = list(
    #   var   = "mxB",
    #   file  = "mx",
    #   scale = "pop",
    #   proj  = FALSE,
    #   age   = TRUE),
    # life_exp = list(
    #   var   = "e0B", 
    #   file  = "e0", 
    #   scale = 1, 
    #   proj  = TRUE, 
    #   age   = FALSE), 
    # fertility = list(
    #   var  = "pasfr", 
    #   file = "percentASFR", 
    #   scale = 0.01, 
    #   proj  = FALSE, 
    #   age   = TRUE))
